### ISSUE TITLE
Still looking for wildcards from /scripts/wildcards and not /extensions/scripts/wildcards

### ISSUE THREAD

**Issue by Evil-Dragon** [AUTOMATIC1111/stable-diffusion-webui-wildcards#1]
I moved all my wildcards over to /extensions/scripts/wildcards since the move to an extension but it's still looking for them in /scripts/wildcards/ 

<img width="195" alt="firefox_lR9auWJKKr" src="https://user-images.githubusercontent.com/9480613/197405361-921c6f15-eae7-432e-804e-f9846d283bb2.png">

If i move them back to /scripts/wildcards/ then it works again and loads them all in as available.

**Comment by a1270** [comment]
Your issue is with the autocomplete addon and it's lack of support for the extension. You'll want to close this bug and file a feature request over at https://github.com/DominikDoom/a1111-sd-webui-tagcomplete
