### ISSUE TITLE
Using Wildcards in the Negative Prompt

### ISSUE THREAD

**Issue by MackinationsAi** [AUTOMATIC1111/stable-diffusion-webui-wildcards#34]
I've looked everywhere & can't find a workaround. Is there any way you could update the extension to include the ability to use wildcards for negative prompts as well?

**Comment by Technomancer-2048** [comment]
Looking for the same.

**Comment by ride5k** [comment]
came here to suggest the same as well

**Comment by MackinationsAi** [comment]
Hey @ride5k & @Technomancer-2048 - Created an updated extension that allows you to use wildcards in both the negative & positive prompts. Here you go [sd-all-prompt-wildcards](https://github.com/MackinationsAi/sd-all-prompt-wildcards)!
